### ISSUE TITLE
Failure during checkout of development branch

### ISSUE THREAD

**Issue by osblinnikov** [GaloisInc/smaccmpilot-build#4]
Step 18 : RUN git submodule update
 ---> Running in 8b5b4256ba15
Cloning into 'ivory'...
Submodule path 'ivory': checked out '55853ac07810d47a35689619aba1375c59a88462'
Cloning into 'ivory-rtverification'...
Submodule path 'ivory-rtverification': checked out 'b4c50f85aea48be2fe26fb3310e01b68b3d163af'
Cloning into 'language-c-quote'...
fatal: reference is not a tree: 20b2032c0765f9c4bad08af6fd388d45b65c2537
...

**Comment by pchickey** [comment]
Thanks for reporting this. We haven't been very good about keeping the top level build repository up to date since we've been so long since a stable release.

If I had to guess, this is probably because we used to track a fork of language-c-quote as a submodule before changes we requested made it into upstream on Hackage. So, perhaps try ignoring any problems with that particular submodule, and let cabal install it from hackage?

I'll try to reproduce this problem and look into a real fix on Monday. Can you send more steps to reproduce - what commands preceded the git submodule update?

**Comment by osblinnikov** [comment]
git clone --recursive https://github.com/GaloisInc/smaccmpilot-build.git
git submodule update
I think the problem was with my docker container, because I've tried to dockerize the build of the smaccmpilot.

BTW, Did you stop the active development of the project? The last commit was on May 30, 2014

**Comment by TomMD** [comment]
@osblinnikov The project is not stopped.  There  are numerous repositories and branches but github is showing you the last commit for `master`.  For example, `features/tower9` has commits as of a month ago and other repositories likely show more recent work.

**Comment by pchickey** [comment]
The project is not dead - Galois has had about 2.5 full time engineers working on this project continuously since late 2012, almost all of that effort on public code, and we expect to keep working on it for at least another 2 years.

The first 18 months of effort on this project were mostly an experiment to see if something ambitious could be done at all, having proved that, we've spent the last 12 or so improving many of the tools we built during the first stage, and making them usable in a broader context.

In the course of redesigning or rewriting many of the low level components in the codebase, we decided to drop the `flight` application from the build until the foundation had settled. We're close to the end of this great upheaval and plan to have `flight` working and flyable again in the next few months, at which point we'll make a fresh release on the `master` branch.

Until then, you can follow our development on the `development` branch in this repo.

**Comment by osblinnikov** [comment]
Thank you very much for the replies. Sorry, I didn't checked all the branches - only master and development. I think we can close this issue.
